### ISSUE TITLE
Change jitpack/pom, new version of openEHR_SDK needed to make feature60/bloodgas compile and runable

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge-old#84]
## Background ##

I require a newer version of the openEHR_SDK as we currently provide in jitpack, in order to compile and implement feature60/bloodgas. There are still a lot of changes to the sdk that are often necessary for implementing mappings (e.g. bugfixes etc.). Hence i would recommend changing the pulled version for the sdk in the pom etc. . Currently im building the openEHR sdk locally, but since i have to merge now we need to solve this. 

Any suggestions/objections ?

## Acceptance criteria ##

_These are the functional requirements for this story. Add all steps to be implemented to fulfill the requirements._

- [ ] Item 1

## Success criteria ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Updated documentation (Javadoc and Sphinx)
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
@ppazos @subigre @wlad

**Comment by ppazos** [comment]
@SevKohler do you have a PR for this?

**Comment by SevKohler** [comment]
> 
> 
> @SevKohler do you have a PR for this?

Not yet, i can submit one tomorrow (i guess). 
I still need verification also from the CI to check if all tests are running there properly (currently failing due to build number of sdk).

**Comment by SevKohler** [comment]
@ppazos here is the pull [request](https://github.com/ehrbase/fhir-bridge/pull/86)

**Comment by wlad** [comment]
new fhir-bridge uses `<ehrbase-sdk.version>develop-SNAPSHOT</ehrbase-sdk.version>`

I think this one can be closed then @SevKohler ?
